### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by Adventure4Life** [Evalir/font-size-switcher-vscode#4]
I do not understand how to use this... I installed the extension ... but now what? I am trying to make my fonts in my editor larger without scaling the entire UI.

**Comment by Evalir** [comment]
Hi! Sorry, this is not maintained anymore. :(

I don't know if it still works, but it was a command that showed up once you pressed `Cmd + Shift + P` on VSCode.

**Comment by Evalir** [comment]
Closing as this package's not maintained anymore.
